FROM public.ecr.aws/lambda/python:3.9

# Copiar requirements básicos
COPY requirements_basic.txt .
RUN pip install -r requirements_basic.txt

# Copiar código de la aplicación simplificado
COPY lambda_app_simple.py .

# Comando por defecto para Lambda
CMD ["lambda_app_simple.lambda_handler"] 